import { drizzle } from 'drizzle-orm/expo-sqlite';
import { migrate } from 'drizzle-orm/expo-sqlite/migrator';
import { openDatabaseSync } from 'expo-sqlite';
import * as schema from './schema';

// Migration files generated by `npm run db:generate`.
// Each .sql file is inlined as a string by babel-plugin-inline-import (see babel.config.js).
// When you add a new migration: import it here and add its tag to the migrations map below.
import journal from './drizzle/meta/_journal.json';
import m0000 from './drizzle/0000_third_brother_voodoo.sql';

// Maps each migration tag (from journal) to its SQL content.
// Add a new entry here every time you run `npm run db:generate`.
const migrationFiles: Record<string, string> = {
  '0000_third_brother_voodoo': m0000,
};

// Open the SQLite file synchronously — Drizzle wraps it with a type-safe query builder.
// `enableChangeListener` lets Drizzle reactively re-run queries when data changes.
const expo = openDatabaseSync('pawstep.db', { enableChangeListener: true });

// The db instance — import and use this everywhere instead of writing raw SQL.
export const db = drizzle(expo, { schema });

// Call once on app start. Applies any pending migrations in order, then no-ops on repeat.
export async function initDb(): Promise<void> {
  await migrate(db, { journal, migrations: migrationFiles });
}
