import { drizzle } from 'drizzle-orm/expo-sqlite';
import { migrate } from 'drizzle-orm/expo-sqlite/migrator';
import { openDatabaseSync } from 'expo-sqlite';
import * as schema from './schema';

// Migration files generated by `npm run db:generate`.
// Each .sql file is inlined as a string by babel-plugin-inline-import (see babel.config.js).
// When you add a new migration: import it here and add its tag to the migrations map below.
import journal from './drizzle/meta/_journal.json';
import m0000 from './drizzle/0000_third_brother_voodoo.sql';

// Maps each migration tag (from journal) to its SQL content.
// Add a new entry here every time you run `npm run db:generate`.
const migrationFiles: Record<string, string> = {
  '0000_third_brother_voodoo': m0000,
};

// Open the SQLite file synchronously — Drizzle wraps it with a type-safe query builder.
// `enableChangeListener` lets Drizzle reactively re-run queries when data changes.
const expo = openDatabaseSync('pawstep.db', { enableChangeListener: true });

// The db instance — import and use this everywhere instead of writing raw SQL.
export const db = drizzle(expo, { schema });

// Call once on app start. Applies any pending migrations in order, then no-ops on repeat.
// Seeds a default pet if none exists so the Home screen has something to display.
export async function initDb(): Promise<void> {
  await migrate(db, { journal, migrations: migrationFiles });
  await seedDefaultPet();
}

async function seedDefaultPet(): Promise<void> {
  const existing = await db.select().from(schema.pets).limit(1);
  if (existing.length > 0) return;

  const { randomUUID } = await import('expo-crypto');
  const now = Date.now();
  await db.insert(schema.pets).values({
    id: randomUUID(),
    name: 'Paws',
    species: 'dog',
    stage: 'baby',
    stamina: 50,
    affection: 0,
    growthValue: 0,
    mood: 'normal',
    isActive: true,
    createdAt: now,
    updatedAt: now,
  });
}
